### ISSUE TITLE
Problem: not generating MSVC solution files

### ISSUE THREAD

**Issue by hintjens** [zeromq/zproject#103]
Solution: take the .sln generators from CZMQ as basis

**Comment by twhittock** [comment]
I've taken a look at this, and I think there's a sticking point which I'd like to discuss with I think @evoskuil

Problem: Using the information currently provided by zproject, we cannot know that libsodium, pgm and so on are *optionally* transitively required by using libzmq.

Currently czmq and all dependent libraries on non-MSVC platforms statically link libzmq dependencies into libzmq, or rely on the shared library being globally accessible. This means that most CZMQ build systems don't care if libzmq has pgm or sodium or whatever linked in - everything just works.

MSVC is currently set up to relink all dependencies past libzmq into every sub-project (czmq, zyre, and so on) explicitly

Possible Solutions:

1. Embrace and extend known_projects to include 'optional' dependencies, which are ignored on most platforms, and resolve into $(use).import.props in MSVC
2. Update the libzmq msvc solution files to statically link in dependencies, so there are no transitive dependencies (apart from the CRT), and hope that users know that they need to make the transitive shared library dependencies available to their app if they want to run it.

I started down the path of 1, backed it out, started 2, backed *that* out and then wrote this. Help. :)

**Comment by hintjens** [comment]
Some other suggestions (it's been a while since I used MSVC so these are
just guesses):

- generate project files with and without dependencies, so user can select
when building
- expose this as an option during zproject generation (we can pass command
switches)

?
Pieter

**Comment by evoskuil** [comment]
@twhittock, I incorporated into the VS UI the option to statically (or dynamically) link a dependency on per-project and/or per dependency basis. For czmq this includes libsodium, and libzmq. The default for each project is to link in the same manner that the project links the C runtime (i.e. static/ltcg or dynamic). VS exposes the option to link the CRT statically or dynamically as well.

There are significant consequences to not following that pattern, but I left it to the user to choose. The various CRT libraries use global state and therefore it is a bad idea to mix them. If one dependency is linked statically to CRT and another dynamically, look out below. So I don't think you want to require static linkage of dependencies, as this basically requires the user to statically link everything that might use CRT, including the main project.

For symbol definition, there are (have) options exposed in the VS UI to enable/disable. This includes openpgm, sodium, gssapi. If one unlinks libsodium he should also disable sodium.

The UI linkage and symbol options and defaults are set up to propagate to dependent projects, via the `*.import.props` files. These options also include the choice to not link a dependency at all (assuming it's unused). However the values selected do not propagate. That must be done manually by the user. There is no equivalent of autoconfig or pkgconfig.

If I better understood the problem scenario I could help, but I don't see it yet.

**Comment by twhittock** [comment]
OK thanks for the response. Perhaps I could rephrase the problem I encountered:

Currently, zproject does not declare libzmq to have any dependencies, but the MSVC projects are aware of them.

Either we remove the need for MSVC to know about the libzmq dependencies, or we add them in to zproject, even though no other build system needs this information.

**Comment by evoskuil** [comment]
I don't see any way to remove knowledge of dependencies from the projects.

The knowledge is encapsulated in:

* libsodium.import.props
* libsodium.import.xml
* libzmq.import.props
* libzmq.import.xml

which are copied from the corresponding projects. These are explicitly referenced from:

* czmq.props
* czmq_selftest.props

I see the problem, but as a general observation I think the approach (not having knowledge of dependencies) will prove undergeneralized. I've spent quite a bit of time on this, as you can see [here](https://github.com/libbitcoin/libbitcoin-build/blob/master/generate.xml). Knowledge of dependencies becomes quite integral.

**Comment by jemc** [comment]
I have no knowledge of MSVC or what is needed for it, but I'll just add zproject already has this notion of "transitive" dependencies (see `use where defined (use.implied)`) - it just doesn't have any notion of "optional" dependencies yet for things like `libsodium`.

The `qt-android` build system uses these "implied" dependencies of known projects in its final `readelf` success check to make sure they are all explicitly linked (otherwise android will be unable to `dlopen` them).

**Comment by twhittock** [comment]
Yes, the issue isn't transitive dependencies, but optional dependencies.

Also the fundamental difference that autotools and I think all other build
systems link these dependencies into libzmq, so downstream projects don't
need to know exactly which compile options to set, while the msvc solutions
currently don't.

**Comment by hintjens** [comment]
Closing as out of date.
