### ISSUE TITLE
Usage of Visual Studio configuration names not consistent

### ISSUE THREAD

**Issue by hambre** [zeromq/zproject#1054]
In file zproject_vs20xx.gsl the visual studio project files are genarated with the following build configuration names: DebugDLL, ReleaseDLL, DebugLTCG, ReleaseLTCG, DebugLIB, ReleaseLIB.
The generated build file build.bat use the following build configuration names: DynDebug, DynRelease, LtcgDebug, LtcgRelease, StaticDebug, StaticRelease (line 705-749).
So building fails with msbuild complaining that the configuration attempted to build does not exists.

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/zproject/pull/1060
