### ISSUE TITLE
Visual Studio: *_private_selftest.c missing from project file

### ISSUE THREAD

**Issue by hambre** [zeromq/zproject#1057]
In build system generated for Visual Studio, the *_private_selftest.c (e.g. czmq_privaty_selfttest.c) is missing from the project files which causes building of the selftest program to fail as the *_private_selftest symbol (e.g. czmq_privaty_selfttest) is then missing from the project library.
Additionally explicit c-linkage is required for the function *_private_selftest (e.g. czmq_privaty_selfttest) so that the selftest binary can be sucessfiully linked.
This issue was found in the czmq project.
Please note that the generator for VS2008 seems to include the *_private_selftest.c into the project file.

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/zproject/pull/1061
