### ISSUE TITLE
Problem: Cannot link with leveldb

### ISSUE THREAD

**Issue by somdoron** [zeromq/zproject#1157]
They use cmake, compile a static library (.a file) and don't install a pc file for pkconfig.

When using it in a project like so:

```
 <use project = "leveldb"
         repository = "https://github.com/google/leveldb.git"
         header = "leveldb/c.h"
         test = "leveldb_open" />
```

cmake does compile but autotools not, fail to configure with `configure: error: cannot link with -lleveldb, install leveldb`

Any ideas?

https://github.com/google/leveldb

**Comment by bluca** [comment]
It should work yes, the linker doesn't care if a lib Is static or dynamic when you pass -lfoo as long as either one is in the default path, I'll have a look tonight

**Comment by bluca** [comment]
@somdoron I tried just now and it seems to be working, is it still an issue?

**Comment by somdoron** [comment]
No really an issue. 
It is only works if you install from package management and not from cmake, they only have cmake and it doesn't provide a pkgconfig file. 

So the questions is, how can I add a dependency that doesn't have a pkgconfig file?

**Comment by bluca** [comment]
the package doesn't have a pkg-config file either - where is the cmake file installing the headers and libs to? I suspect it's simply going into /usr/local - in which case the paths have to be added manually as the linker and the compiler won't look in there by default on most distros

**Comment by bluca** [comment]
if so, you can either pass --with-leveldb=/usr/local as the configure.ac helper says https://github.com/zeromq/dafka/blob/master/configure.ac#L337 or add manually the -I and -L flags as the ci_build.sh does https://github.com/zeromq/dafka/blob/master/ci_build.sh#L116 (the former is easier)

**Comment by somdoron** [comment]
thanks, my machine is configured to take from /usr/local as well.

Thanks.
