### ISSUE TITLE
Problem: python target fails when bindings/python directory does not exist

### ISSUE THREAD

**Issue by lbotsch** [zeromq/zproject#1164]
When adding
```xml
<target name="python"/>
```
to a project.xml and regenerating, gsl fails saying:
`(zproject_python.gsl 245) Can't open output file: bindings/python/setup.py`

One has to create the bindings/python directory manually
`mkdir -p bindings/python`

**Comment by bluca** [comment]
Probably a ```directory.create``` is missing from https://github.com/zeromq/zproject/blob/master/zproject_python.gsl#L244 could you please send a PR to fix it?
