### ISSUE TITLE
Remove usage of Java Stream

### ISSUE THREAD

**Issue by Crisaldroid** [zeromq/zproject#1194]
Java bindings seems to use the stream API from Java 8 just for convenience [here.](https://github.com/zeromq/zproject/blob/3e60ac212c0977bb4d06d89184af39863ee9a8bb/zproject_java.gsl#L814) Is it possible to change that ?

The problem is that break compatibility with Android devices with API level < 24..

**Comment by bluca** [comment]
@sappo any chance you could have a look? Thanks!

**Comment by sappo** [comment]
Sure, would you like to send a PR?
