### ISSUE TITLE
CI test fails on missing bindings dir

### ISSUE THREAD

**Issue by sphaero** [zeromq/zproject#1216]
Since some time Travis fails on my project because of a missing bindings dir.

As I'm not using bindings, what is wise? Create an empty bindings dir or fix the test?

See for example: https://travis-ci.org/hku-ect/libsphactor/jobs/636905306?utm_medium=notification&utm_source=github_status

```
make  dist-gzip dist-zip am__post_remove_distdir='@:'
make[1]: Entering directory '/home/travis/build/hku-ect/libsphactor'
Python Bindings not enabled or missing setup.py... skipping
make[1]: Circular src/selftest-ro <- src/selftest-ro dependency dropped.
if test -d "libsphactor-0.1.0"; then find "libsphactor-0.1.0" -type d ! -perm -200 -exec chmod u+w {} ';' && rm -rf "libsphactor-0.1.0" || { sleep 5 && rm -rf "libsphactor-0.1.0"; }; else :; fi
test -d "libsphactor-0.1.0" || mkdir "libsphactor-0.1.0"
cp: cannot stat './bindings': No such file or directory
Makefile:1312: recipe for target 'distdir' failed
make[1]: *** [distdir] Error 1
make[1]: Leaving directory '/home/travis/build/hku-ect/libsphactor'
Makefile:1410: recipe for target 'dist' failed
make: *** [dist] Error 2
The command "./ci_build.sh" exited with 2.
```

**Comment by bluca** [comment]
I'd say the test should be fixed, if there are no bindings it shouldn't fail

**Comment by sphaero** [comment]
Any idea where the change happened that triggered this?

**Comment by bluca** [comment]
Sorry, can't say off the top of my head

**Comment by sphaero** [comment]
This is not a bug in zproject but just a warning that if you regenerate of project and you do have a bindings dit this problem will occur. Just remove the bindings dir and regenerate!
