### ISSUE TITLE
Problem: projects not up to date

### ISSUE THREAD

**Issue by mjvankampen** [zeromq/zproject#1266]
I am working on a change in cmakelists, but after doing a regen many more files change. For example the zcertstore state function in CZMQ and zyre, android and gradle version, zsock_new_dgram etc. in malamute. I think these changes should be integrated first correct?

I made draft PRs to these projects, but not sure if these are OK. It does seem to be necessary as ```CZMQ_EXPORT void *
    zcertstore_state (zcertstore_t *self);``` is not exposed in the bindings.

**Comment by sappo** [comment]
@mjvankampen the regen part is a natural why to keep up with changes from zproject. Thereby it usually doesn't matter if they're integrated one by one.

You can undraft these PR an I'll merge them
