### ISSUE TITLE
Documentation files are not generated correctly for classes

### ISSUE THREAD

**Issue by mvala** [zeromq/zproject#131]
when i run ./generate.sh documentation files (doc/*.txt) for classes are not generated correctly. Only name of the class is in the file.

**Comment by mvala** [comment]
When i use mkman on each file it generates doc correctly for classes. Can you give me hint what to do?

**Comment by hintjens** [comment]
There is a problem with the man page generator. I'll look at it today. You
can work around by running zproject_mkman for offending classes, in doc.

**Comment by mvala** [comment]
This is what i did. Thanks for your hard work
