### ISSUE TITLE
No rule to make target 'zproject.gsl'

### ISSUE THREAD

**Issue by mvala** [zeromq/zproject#134]
i am getting following error. Do we need to have *.gsl in generated project? Isn't it enough to have *.gsl files in /usr/loca/bin?

```
make[1]: Entering directory '/home/mvala/MVALA/git/saske/mvala/zmon/doc'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/mvala/MVALA/git/saske/mvala/zmon/doc'
make[1]: Entering directory '/home/mvala/MVALA/git/saske/mvala/zmon'
  CC       src/src_libzmon_la-zmon_gtop.lo
  CCLD     src/libzmon.la
make[1]: *** No rule to make target 'zproject.gsl', needed by 'all-am'.  Stop.
make[1]: Leaving directory '/home/mvala/MVALA/git/saske/mvala/zmon'
Makefile:1000: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by jemc** [comment]
You don't want to add zproject.gsl to your Makefile.
Instead, copy the `generate.sh` script and `project.xml` to your project root, customize the `project.xml` model, and run `./generate.sh` by hand whenever you change your model or want to regenerate.

**Comment by mvala** [comment]
Thus is what i did. I started with 3 files on empty directory. generate.sh, project.xml and license.xml.

**Comment by twhittock** [comment]
This happens if you copy the whole of zproject's project.xml and don't delete the <bin name="blah" /> nodes. I think this could be made easier to understand and get started with by having an example project in zproject, maybe?
