### ISSUE TITLE
Problem: Ruby Finalizers are broken

### ISSUE THREAD

**Issue by Asmod4n** [zeromq/zproject#160]
In Short: because of the way the finalizers are created they cannot be run.

Solution:
something like this may work, cannot test it myself for the upcomming days.
```ruby
def initialize(ptr, finalize = true)
  @ptr = ptr
  @finalize = finalize
  if @ptr.null?
    @ptr = nil
  elsif @finalize
    ObjectSpace.define_finalizer(@ptr, self.class.create_finalizer_for(@ptr.address))
  end
end

def self.create_finalizer_for(ptr_address)
  ->(obj_id) do
    ptr = FFI::MemoryPointer.new(:pointer)
    ptr.write_pointer(FFI::Pointer.new(ptr_address))
    ::$(project.RubyName:)::FFI.$(class.c_name)_$(destructor.c_name) ptr
  end
end
```

**Comment by jemc** [comment]
@Asmod4n 
Do you have any evidence for your claim?
I have been using these finalizers in my projects, and have confirmed their execution on MRI 2.1.x and Rubinius 2.x

I created a small example repository as a minimal sandbox to test with just this morning, and they appear to work.
https://github.com/jemc/zproject_ruby_finalizer_test
To test it, clone, `make install` the C library, and run `./test.rb` with the Ruby of your choice.  The "chatty" objects will print to zsys_debug when created and when destroyed.  You should see a long list of created objects, then start to see some of them destroyed when the GC kicks in.

**Comment by Asmod4n** [comment]
This was just out of memory, afaik you cannot store the finalizer in a instance variable without it causing some trouble, because of a backward dependency.

**Comment by jemc** [comment]
I don't think such a constraint exists - when the instance is no longer reachable, the finalizer isn't reachable either as long as it is held *only* in the instance variable, so both are able to be freed.  My tests so far seem to indicate it's working okay as-is, so I'm closing for now.

Of course, if you can show that there is a problem in the future feel free to reopen this issue or make a PR.  I definitely want this stuff to be working correctly as much as you do.

**Comment by Asmod4n** [comment]
Will do, if i got time i might add a mruby binding too :)
