### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [zeromq/zproject#167]
I would like to point out that the use of [double underscores](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?") in [specific identifiers](https://github.com/zeromq/zproject/blob/14fe7d5dc0c004a2872321dce7b6b9dac2e0ed84/zproject_class.gsl#L36 "Update candidates") [does not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL32-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL32-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by jemc** [comment]
Resolved by #168
