### ISSUE TITLE
Complete quoting for parameters of some CMake commands

### ISSUE THREAD

**Issue by elfring** [zeromq/zproject#170]
Some parameters (like "[${SOURCE_DIR}/include](https://github.com/zeromq/zproject/blob/cf5c2c0b38f3de71ca5ca007225770920f1821cc/zproject_cmake.gsl#L126)") are passed to CMake commands in your build script without enclosing them by quotation marks. I see that these places will result in build difficulties if the contents of the used variables will contain special characters like semicolons.

I would recommend to apply [advices from a wiki article](http://cmake.org/Wiki/CMake/Language_Syntax#CMake_splits_arguments_unless_you_use_quotation_marks_or_escapes. "CMake splits arguments unless you use quotation marks or escapes.").

**Comment by twhittock** [comment]
So this is fixed by #171 right?
