### ISSUE TITLE
Problem: No convienient way to generate actor skeleton

### ISSUE THREAD

**Issue by sappo** [zeromq/zproject#183]
While working on a new project I found myself creating multiple actors. I used zproject to generate the class skeleton which worked all nicely but then I needed to manually adjust the header and source files to add the actor method startup and shutdown functionality. As actors very useful, I like to add skeleton generation for them. I would like your input on how to do this in the project.xml:

Option 1: 
```
<class name = "myactor" type = "actor" private = "0|1"></class>
```

Option 2: 
```
<actor name = "myactor" private = "0|1"></actor>
```

**Comment by hintjens** [comment]
It's a one-off generation, isn't it?

So it doesn't need any addition to the project model. You can create a gsl script that produces a new actor (if the files do not already exist), filling in the blanks from command line arguments.

**Comment by sappo** [comment]
The same way we use zproto? E.g.
```
<model name = "myactor" script = "zproject_actor.gsl" />
```
or
```
<model name = "myactor" script = "zproject_actor.gsl">
    <param name = "private" value = "1" />
</model>

**Comment by hintjens** [comment]
Yes, defining a model is simple and clean. If you're going to generate actors (and I like the idea), maybe we can think a little bit about that... e.g. take the client generator and strip it down... KISS.

**Comment by sappo** [comment]
I already have something working. You can have a look here: https://gist.github.com/sappo/1840fc1ecef8c56e69cf.

This currently uses Option 2 from above. If you look closely it is a stripped down version of the zyre_node actor.

**Comment by hintjens** [comment]
OK, in the interests of reducing surface area I think the model hook is the
right place; we can then expand on the actor model language without
affecting zproject (and it really is a different layer).

**Comment by sappo** [comment]
IMO this model would rather fit zproto than zproject.

**Comment by hintjens** [comment]
Yes, it should perhaps go into zproto. It doesn't matter to zproject where
you put the GSL script; as long as it's installed and accessible when you
run "make code".

**Comment by sappo** [comment]
Great, thanks for your input. I'll go to work then :)

**Comment by twhittock** [comment]
A bit late here, but from the perspective of binding generation, zproject would be better - currently it's a bit difficult to know what to do with an actor method compared to a regular method - it's not *callable* like a regular method, so the distinction matters.

**Comment by twhittock** [comment]
To illustrate what I mean above, an actor is not a `<method>` element - it is an `<actor>` element - it is not callable, it has its own request/response structure (which could be structured in the definition and auto-generate the documentation) and could be interpereted differently by the various binding generation targets to generate a class or whatever based on this information, if it was made a part of the CLASS structure. It's not 100% one-time as the interface to an actor may change over time.

**Comment by jemc** [comment]
I like the idea of making zproject actor-aware (the current way of zproject-binding actors is fairly clumsy as @twhittock described).  Not sure how this should look though...

**Comment by twhittock** [comment]
I was thinking something like this, in place of the `<method>` which currently goes there:

```
<actor name="watch">
    <message name="subscribe">
        Subscribe to changes to a directory path
        <argument name="directory" type="string" />
    </message>
    <recv type="zlist" />
</actor>
```

**Comment by hintjens** [comment]
This is a random comment; could we use spaces around '=' in XML files,
matching what's been done in all other cases before the API files?

**Comment by sappo** [comment]
@twhittock I do understand your approach but I think it is a bit clumsy. What you're doing is combining actor and codec generation which IMO should be two separate things. Furthermore from a user's perspective adding an actor to a project should be at most 1 line of xml code.

**Comment by sappo** [comment]
Okay I went the extra mile and added actor generation to both zproject and zproto. Here's the good and bad. I highlighted the necessary changes to zproject:

#### zproto
project.xml
```
<model name = "my_actor" script = "zproto_actor_c.gsl"></model>
<--! Needed for Makemodule, header and selftest generation -->
<class name = "my_actor" private = "1" ></class>
```
src/my_actor.xml
```
<class
    name = "my_actor"
    script = "zproto_actor_c"
    package_dir = "."
    source_dir = "."
    >
    <include filename = "../license.xml" />
</class>    
```
##### Pro
* No changes to zproject necessary.

##### Contra
* Does not fit the `make code` paradigm as its one time generation.
* Need an XML file for each actor (like we do have for the codec).
* Need to manually add actors to Makemodule, private or public header and selftest every time zproject is generated (the same thing currently is the case for codecs). If we add an class entry like I did above this issue is solved but it is confusing as the CLASS skeleton is generated and than overridden by `make code`.

#### zproject
project.xml
```
<actor name = "my_actor" private = "1" ></actor>
```
##### Pro
* Easier to understand from a users perspective (IMO).
* Automatically generate Makemodule, private or public header and selftest entries for an actor.

##### Contra
* Modifies the zproject model. As actors are extremely important to write multi threaded zeromq application and they're something different than just plain classes this seems justifiable.
* Need to map actors to classes to achieve the automatic generation. With my `<actor/>` approach that means adding an implicit class entry with gsl. Which also means that actor generation will need to happen before class generation.

I used both approaches over the weekend and the zproject one definitely made me happier as a user. What do you guys think? Am I missing something on the pro or contra side?

**Comment by hintjens** [comment]
If it makes you happy when you use it, that's pretty much the acid test.
Looks good!
