### ISSUE TITLE
python 3 compatibility

### ISSUE THREAD

**Issue by sphaero** [zeromq/zproject#189]
It seems the python binding generation is incompatible with python3

Around https://github.com/zeromq/zproject/blob/master/zproject_bindings_python.gsl#L297
(convenience) methods are used which are deprecated in python 3 because of the newer io system.

from: https://docs.python.org/3.3/c-api/file.html
```
These APIs are a minimal emulation of the Python 2 C API for built-in file objects, which 
used to rely on the buffered I/O (FILE*) support from the C standard library. In Python 3, 
files and streams use the new io module, which defines several layers over the low-level 
unbuffered I/O of the operating system.
```
If you look at https://docs.python.org/2.7/c-api/file.html you can see many methods are gone in python3. 2to3 is not taking this into account therefore the bindings fail in python3.

refering to: https://github.com/zeromq/czmq/issues/998

**Comment by jemc** [comment]
@sphaero - If you or someone else with python knowledge wanted to take a look at improving this, that would be great.  The bindings generator for python was originally written by @twhittock - maybe he/she has some input.

I wonder if it is possible to support both python 2 and python 3 with the same bindings?  If so, finding a way to do that would likely be best.  If not, there would be no problem with adding a second generator that targets python3 (or uses FFI instead, or other procedural differences).

**Comment by sphaero** [comment]
I think it is possible to support both py2 and 3. However the new io systems needs to be used which I think is available in py2 as well. I'll take a look at it but I'd have to admit this is new to me as well. If someone could elaborate on what these methods are doing exactly.

**Comment by twhittock** [comment]
I wrote these bindings. I didn't consider Python3 compatibility when doing so beyond 'obvious' basics. The `*_AsFile` and `*_FromFile` methods are called to provide a sane API to callers. There's no reason the bindings *have* to call these functions, but if they didn't, then the calling Python code would have to work out how to interpret a C FILE* structure and convert it into a Python file itself.

It looks like Python 3 makes this hard to do. I feel this is a general trend with Python 3, and I'm not particularly interested in supporting it, personally.

To fix this, you'll have to use the stuff from https://docs.python.org/3.3/c-api/file.html as well as the stdlib functions like `fdopen` and `fileno` to convert between Python files and C FILE* pointers. The solution probably won't be cross-compatible between Python 2 and 3, and will introduce problems with 2 different systems buffering the data.

**Comment by twhittock** [comment]
A different approach would be to create a file-like object which used stdlib file access functions to implement the functionality. That'd be compatible between 2 & 3, and avoid buffering issues.

**Comment by sphaero** [comment]
I'd have to dive into this. Python 3 compat is essential as most apps I know of all embed python3.
From what I know in python3 some inconsistencies have been fixed. The biggest problem I always run into is that you have think in bytes while in python2 most datatypes you could use directly you'd have to make sure you get the bytes now. I've had lots of trouble with that in the beginning as well but now I understand it it makes sense.

Are the methods you mention just methods to access files? Or are they used for other purposes as well? (filedescriptors?)

**Comment by twhittock** [comment]
This is purely to do with file IO, nothing to do with Unicode.

The problem is that python 3 has introduced some sort of custom buffering
solution instead of using the c library standard, like in python 2,
breaking API compatibility.

Creating a custom file-like object in python which calls fread, fwrite, etc
could be one solution to work around this incompatibility.

I have no idea what is required to make such an object compatible with both
python 2 & 3.

I'd be happy to see this work, but am not particularly interested in it for
myself.

Hope that helps.
