### ISSUE TITLE
Problem: CZMQ uses pthread symbols, but does not link to it

### ISSUE THREAD

**Issue by bluca** [zeromq/zproject#199]
Commit https://github.com/zeromq/czmq/commit/5ea2e8123818f96099cb5c3c7948e3bdfec1cf69 changed to use zproject's auto-generated configure.ac and Makefile.am, but in the process this was lost:

    AC_CHECK_LIB([pthread], [pthread_create])

And when building the library, -pthread is not used.

Among the other problems, this causes warnings when building a Debian package:

    dpkg-shlibdeps: warning: symbol pthread_mutex_trylock used by
     debian/libczmq3/usr/lib/x86_64-linux-gnu/libczmq.so.3.0.0 found in none
     of the libraries
    dpkg-shlibdeps: warning: symbol pthread_detach used by
     debian/libczmq3/usr/lib/x86_64-linux-gnu/libczmq.so.3.0.0 found in none
     of the libraries
    dpkg-shlibdeps: warning: symbol pthread_create used by
     debian/libczmq3/usr/lib/x86_64-linux-gnu/libczmq.so.3.0.0 found in none
     of the libraries

The diff for the generated configure.ac and Makefile.am is really trivial:

    +--- a/configure.ac
    ++++ b/configure.ac
    +@@ -69,6 +69,13 @@
    +     fi
    + fi
    + 
    ++# Checks for libraries
    ++AC_CHECK_LIB([pthread], [pthread_create], [
    ++       have_pthread=yes
    ++       pthread_LIBS="-pthread"],
    ++    [AC_MSG_ERROR([pthread is required for this program])])
    ++AC_SUBST(pthread_LIBS)
    ++
    + PREVIOUS_CFLAGS="${CFLAGS}"
    + PREVIOUS_LIBS="${LIBS}"
    + 
    +--- a/Makefile.am
    ++++ b/Makefile.am
    +@@ -10,6 +10,7 @@
    +     -I$(srcdir)/include
    + 
    + project_libs = \
    ++    ${pthread_LIBS} \
    +     ${zmq_LIBS}
    + 
    + SUBDIRS =

But I cannot see where/how to do it in the template, in a way that's optional and it would apply only to CZMQ and not to other projects.

Does anyone have any pointer? I'm happy to do a PR once I figure it out :-)

**Comment by twhittock** [comment]
That change was back in February - czmq has been building fine for months
since then, on many different platforms.

Can you tell me what version of libzmq you're linking against? master?

**Comment by bluca** [comment]
Hi,

The background is that I'm doing Debian packaging, and I am packaging CZMQ 3.0.2, built against ZMQ 4.0.5.

To clarify, it does build just fine, and I think the reason why there are no visible issues on any platform is that since ZMQ is linked against pthread, the programs using CZMQ will build just fine since it's a dependency.

The problem is that Debian's (and Ubuntu's and other .deb based distros) build system will see that the library uses symbols but cannot resolve them as there's no linkage to pthread, and so it shows an error, since it expects the right thing to be done and all the symbols to be accounted for. :-)

**Comment by bluca** [comment]
Since there's currently no way in Zproject to express a dependency on a standard library module like Pthread or Math, would you accept a PR that adds project-local hooks for Autoconf and CMake, just like the current one for Automake? This way, the flags can be added locally if needed.

**Comment by sappo** [comment]
Yes, there is one rule though, keep the main configuration free of any configuration specifics. Also try to keep things as simple a possible.

**Comment by bluca** [comment]
Ok, will do a PR later tonight. Thanks!

**Comment by bluca** [comment]
Done: https://github.com/zeromq/zproject/pull/202
