### ISSUE TITLE
Problem: when request zyre in my project, it wants to have czmq 3.1.0

### ISSUE THREAD

**Issue by mvala** [zeromq/zproject#200]
In zproject_known_projects.xml there is
```
    <use project = "zyre"
        repository = "https://github.com/zeromq/zyre"
        test = "zyre_test">
        <use project = "czmq" min_major = "3" />
    </use>
```
when i add to my project.xml

```
<use project = "zyre" min_major= "1" min_minor = "1" min_patch = "0" />
```
i am getting following error
```
checking for czmq... no
configure: error: Cannot find required package for libczmq. Note, pkg-config is required due to specified version >= 3.1.0
```
Since czmq 3.1.0 doesn't exists.

I am going to do merge request to fix it soon

**Comment by hintjens** [comment]
Good catch. GSL pulls unspecified properties from parent scopes by default.
You could fix the <use> to explicitly specify the minor version. Or, use an
explicit scope where that is referenced.
