### ISSUE TITLE
Problem: ruby bindings aren't very ruby like

### ISSUE THREAD

**Issue by Asmod4n** [zeromq/zproject#204]
Currently trying to work with the czmq ruby bindings, the code you have to write to make it work is very c like

As far as i can see, no exceptions are thrown but null pointers and "error codes" instead.
Zmsg.recv for instance requires one to dig into the source code and find out there is no #to_ptr method for a Zsock instance, but only a #__ptr method.

```ruby
FFI.errno = 0
zmsg = Zmsg.recv zsock.__ptr
if zmsg.null?
  raise SystemCallError.new("Zmsg.recv", FFI.errno)
end
first_frame = zmsg.first
puts first_frame.data.read_bytes(first_frame.size)
until (next_frame = zmsg.next).null?
  puts next_frame.data.read_bytes(next_frame.size)
end
```

This could be done like this
```ruby
zmsg = Zmsg.recv zsock
zmsg.each do |zframe|
  puts "frame contents: #{zframe}"
end
```

ruby-ffi looks for a #to_ptr method on every object which is not a FFI Object and calls it automatically, so a renaming of #__ptr to #to_ptr would solve the issue in the first line.

Basic Error checking could be done too. Something like this for functions which return a int.
```ruby
FFI.errno = 0
if some_method_call == -1
  raise SystemCallError.new(FFI.errno)
end
```
Something like a Zframe could get a #to_str method which would turn a Zframe into a ruby String.

I believe when it comes to direct interaction with FFI and C error checking it should be done in zproject.
Exposure of high level ruby functionality could be done in a high level wrapper.

**Comment by jemc** [comment]
Renaming `#__ptr` to `#to_ptr` sounds like a great idea based on the FFI behavior you mentioned (assuming no one defines a `to_ptr` method in a zproject-wrapped library, which I think is okay to assume for now).

> Exposure of high level ruby functionality could be done in a high level wrapper.

In general, this is what I've been doing in projects that use this - there are essentially three layers at play here:
1. The FFI `attach_function`s (generated by zproject).
2. The basic object wrappers in the `<ProjectName>::FFI` namespace (generated by zproject).
3. The high-level idiomatic object wrappers in the `<ProjectName>` namespace (written by hand).

So, there's no way the low-level wrappers will ever be fully idiomatic Ruby, as we have to keep the general case in mind for all projects using zproject (not just CZMQ), but I agree they can be improved in some ways.

Regarding `errno` - we can't assume all int-returning methods have the `-1`-sets-`errno` semantic, but there may be a way for us to mark `errno`-setting methods from the `api/*.xml` files with an extra property.  Come up with a minimal PR that just addresses that issue (or a plan for such a PR) and I bet we can make it work. 

So, I definitely want you to be empowered to make improvements to the Ruby bindings here, but keep in mind that I do have apps that depend on these bindings that I need to keep running, so let's take it one problem at a time (like the `to_ptr` method and separately, the `errno` handling).

**Comment by Asmod4n** [comment]
Regarding errno, should be really simple to check for errno == 0 and result == -1 and then raise a custom error class instead of a SystemCallError.

**Comment by jemc** [comment]
But if you're talking about having the wrapper handling that automatically, you can't assume that a result of `-1` means "check `errno`" for all methods that return an `int` - some methods will return `-1` to mean something that has nothing to do with `errno` and the code generator can't know which is which unless you tell it (by marking the methods somehow in their `api/*.xml` file.

**Comment by Asmod4n** [comment]
ok, good :) ill tackle the ptr issue now.

**Comment by Asmod4n** [comment]
Regarding error handling, some methods also return NULL (zpoller_wait) to indicate "nothing to return, but everything is fine".

**Comment by jemc** [comment]
Right, so there needs to be various "return value semantics" strategies marked somehow in the API XML files.

**Comment by hintjens** [comment]
I'm closing this as too vague. It applies to all the generated bindings. If you can find specific things to improve, it's worth it. Long-running issues are not a good idea.
