### ISSUE TITLE
Problem: cannot specify "uint32_t" as a type in zproject_class_api.gsl

### ISSUE THREAD

**Issue by Asmod4n** [zeromq/zproject#210]
The ZMQ_SERVER and CLIENT sockets got a routing id which is a uint32_t, while it should be harmless to use size_t for that.

Solution:
add a "positive_number" type where the size can be specified.

**Comment by sappo** [comment]
This is possible since #235 e.g.
```xml
<argument name = "routing id" type = "number" size = "4" />
```
