### ISSUE TITLE
Problem: class api generators cannot specify arguments as optional/nullable

### ISSUE THREAD

**Issue by Asmod4n** [zeromq/zproject#215]
Currently looking into writing a mruby generator, some projects have method/constructor arguments which can either be a c string or NULL, mruby has a special argument type for that, where you can pass a string or nil value, or make that argument optional.

As far as i can see, the api generators don't have a way to tell if you can pass nil or omit that argument completely and default it to NULL.

**Comment by Asmod4n** [comment]
The three different ways how you can pass a string to a mruby method.

```c
//  everything after a dash is optional, must come at the end
static mrb_value
mrb_method_with_optional_arg(mrb_state *mrb, mrb_value self)
{
    char *arg = NULL;

    mrb_get_args(mrb, "|z", &arg);

    return self;
}

// only allows strings
static mrb_value
mrb_method_with_string_arg(mrb_state *mrb, mrb_value self)
{
    char *arg;

    mrb_get_args(mrb, "z", &arg);

    return self;
}

// allows strings or nil, which sets arg to NULL
static mrb_value
mrb_method_with_nullable_string_arg(mrb_state *mrb, mrb_value self)
{
    char *arg;

    mrb_get_args(mrb, "z!", &arg);

    return self;
}
```

**Comment by sappo** [comment]
I guess there are couple of languages that support optionals. Therefore, I would suggest to add an optional attribute to the `argument` tag, e.g.:
```xml
<method name = "method with optional argument">
        <argument name = "arg1" type = "string" />
        <argument name = "arg2" type = "string" optional = "1" />
</method>
```
The default behavior if the attribute doesn't exists is: not optional.

**Comment by hintjens** [comment]
The same issue as #378, really.

I like the 'optional' attribute. I assume it applies from last-to-first so we can validate this in zproject_class_api.gsl?

**Comment by Asmod4n** [comment]
Should be doable, every language i know puts optionals at the end.

On a Sidenote, in c you can override functions like this, or?
```c
int func(char *arg_one);

int func(char *arg_one, char *arg_two);
```

**Comment by hintjens** [comment]
In C you can't do this, no.

**Comment by jemc** [comment]
The `optional` attribute sounds good to me.

**Comment by hintjens** [comment]
I'm hitting this issue in Zyre with Node.js and will add an `optional` property, experimentally.
