### ISSUE TITLE
zproject_mkman is required on the build host

### ISSUE THREAD

**Issue by jimklimov** [zeromq/zproject#257]
Problem: the generated Makefiles end up requiring zproject_mkman to build manpages. If the project files are stored into Git and the build host has no zproject nor even gsl installed, they are in trouble.
Solution: make it optional, or deliver the script/recipe among generated project files so it is guaranteed to exist.

**Comment by hintjens** [comment]
Indeed, we could generate mkman into the doc directory and remove the dependency on zproject_mkman. That's a nice idea!
