### ISSUE TITLE
(usability): ZProject returns project.xml errors one by one

### ISSUE THREAD

**Issue by jimklimov** [zeromq/zproject#260]
Problem: if the project.xml lacks some required fields, etc., then zproject reports the first error and quits. This causes a need for several iterations to fix the basic issues.

Solution: add a mode like "make -k" to not abort on errors and report more of them at once.

**Comment by sappo** [comment]
Zproject uses gsl to do the generation and there's no such option for gsl.

**Comment by hintjens** [comment]
Well, it's possible to validate the XML before starting code generation.
However that can lead to other issues. Maybe some basic validation would be
useful. What I'd suggest otherwise are better defaults so that an emptier
project file still works...
