### ISSUE TITLE
Ruby bindings: format arguments

### ISSUE THREAD

**Issue by paddor** [zeromq/zproject#292]
I've noticed that the format arguments aren't processed correctly. Given the following API declaration (example from `zsock.xml`):

```xml
      <method name = "connect">
          Connect a socket to a formatted endpoint
          Returns 0 if OK, -1 if the endpoint was invalid.
          <argument name = "format" type = "format" />      # this is the relevant line
          <return type = "integer" />
      </method>
```

which corresponds to the following C function declaration:

```C
  //  Connect a socket to a formatted endpoint
  //  Returns 0 if OK, -1 if the endpoint was invalid.
  CZMQ_EXPORT int
      zsock_connect (zsock_t *self, const char *format, ...) CHECK_PRINTF (2);
```

It produces the following (correct) FFI binding:
```ruby
        attach_function :zsock_connect, [:pointer, :string, :varargs], :int, **opts
```

But the following low-level Ruby binding method:
```ruby
      # Connect a socket to a formatted endpoint        
      # Returns 0 if OK, -1 if the endpoint was invalid.
      def connect format, result
        raise DestroyedError unless @ptr
        format = String(format)
        result = ::CZMQ::FFI.zsock_connect @ptr, format, result
        result
      end
```

Apart from the very wrongly named second parameter, it's also makes calling this method impossible.

The method should actually use a variable length argument list as well, and pass them to the FFI-bound method, as follows:

```ruby
      # Connect a socket to a formatted endpoint        
      # Returns 0 if OK, -1 if the endpoint was invalid.
      def connect format, *args
        raise DestroyedError unless @ptr
        format = String(format)
        result = ::CZMQ::FFI.zsock_connect @ptr, format, *args
        result
      end
```

Now, I tried to find code responsible for this bug inside https://github.com/zeromq/zproject/blob/master/zproject_bindings_ruby.gsl, but couldn't find it. I guess there has to be a new condition added: If an argument in the API-XML is of type `format`, then another argument has to be added, which will take up all the remaining arguments during a call.

If someone knows how to do this off the top of their head, I'd be very grateful.

Otherwise I guess I'll have to read up on GSL.

**Comment by jemc** [comment]
At the time I created these bindings, the `format` argument type did not exist in zproject.  However, I don't have spare time to add this right now, so I suggest reading up on GSL :grin:.

**Comment by paddor** [comment]
Closing this issue as it's fixed now.
