### ISSUE TITLE
Problem: api files cannot handle methods that require a spefic version of a library

### ISSUE THREAD

**Issue by sappo** [zeromq/zproject#308]
An example from czmq (zsock.h):
```c
#if ZMQ_VERSION_MAJOR >= 4 && ZMQ_VERSION_MINOR >= 2

CZMQ_EXPORT zsock_t *
    zsock_new_server_checked (const char *endpoint, const char *filename, size_t line_nbr);

CZMQ_EXPORT zsock_t *
    zsock_new_client_checked (const char *endpoint, const char *filename, size_t line_nbr);

#endif
```

**Comment by sappo** [comment]
Okay, my first idea is to add a `since` attribute and fill it with the `#if` check. The upside of this approach is, that we can easily rebuild our current `#if` checks and even group methods with the same check to minimize clutter. The downside is that zproject cannot parse these expressions thus bindings cannot act on them.

```xml
<method name = "zsock_new_server_checked" 
        since = "ZMQ_VERSION_MAJOR >= 4 && ZMQ_VERSION_MINOR >= 2">
   ...
</method>

<method name = "zsock_new_client_checked" 
        since = "ZMQ_VERSION_MAJOR >= 4 && ZMQ_VERSION_MINOR >= 2">
   ...
</method>
```

**Comment by jemc** [comment]
@sappo - Even if these expressions were in a format that were semantically extracted into the model, how would the zproject-generated bindings be able to act on them?

I'm wary of going too deep down this rabbit hole with zproject for this very czmq specific stuff.

**Comment by sappo** [comment]
@jemc That's probably true. But in C it is common practice, not sure if `good practice` though, to ifdef methods with some condition(s). So instead of a `since` we can have a `condition` that is checked with ifdefs. But this will bind the api model explicitly to C and drag us into the "rabbit hole". So the question is: Are we solving the problem for czmq exclusively or might this be valid for other c projects as well?

@hintjens Do you think we can solve this issue in czmq?

**Comment by twhittock** [comment]
A tangent but those conditions will fail when zmq gets to v5.0, since the
minor version check will fail.

There is usually a combined version integer in many projects which resolved
to eg 402 for v4.2, so a basic >= check can be done without falling into
this trap.

**Comment by sappo** [comment]
@twhittock good catch. There is `ZMQ_VERSION >= ZMQ_MAKE_VERSION (4, 2, 0)`. Nevertheless should we implement this "feature"?

**Comment by paddor** [comment]
What about taking a similar approach as in CZMQ's sockopts? See the [XML](https://github.com/zeromq/czmq/blob/master/src/sockopts.xml) and the [GSL snippet](https://github.com/zeromq/czmq/blob/master/src/sockopts.gsl#L6-L14). It allows macro-like expansion of methods and append them to `<version>` nodes.

To avoid having to adapt all the binding generators, we could mark one of the `<version>` nodes as default (possibly deduced from the current project's `<version major = "x" minor = "y" patch = "z" />` node) and copy that interface (constructors, destructors, methods) into the `<class>` node.

Bindings which want to support more than the current major version would have to iterate through the `<version>` nodes and make them accessible through version-specific interfaces, possibly determined at runtime, depending on the actual loaded shared library version.

**Comment by jemc** [comment]
@paddor Note that the functions in question in CZMQ are not depending on the CZMQ version, but on the LIBZMQ version.  I think this aspect makes it much more difficult to be useful here.

**Comment by paddor** [comment]
@jemc True. Totally missed that. In that case, if @twhittock's approach is possible, I think it's a nice idea.

But what would it mean for the bindings? It'd be possible that one method is defined twice in the API, with different conditions in C preprocessor syntax. Or just that the method isn't actually available in the shared library.

**Comment by sappo** [comment]
I did a through lookup of all czmq include files and those in question are:
* zarmour.h
* zmonitor_v2.h
* zsock.h
* zsock_option.h
* zsockopt.h
All of those depend solely on the `ZMQ_VERSION` thus the issue is "very czmq specific stuff" as @jemc argued. Therefore implementing a workaround in zproject seems not appropriate and we should rather fix the problem in czmq.

**Comment by twhittock** [comment]
I was credited with an approach earlier, but didn't suggest one, I merely
made a pedantic comment. I'm not sure what was being referred to there.

My suggestion would be to explicitly *not* solve this in zproject. The
reason for this is that it changes the binary interface of the dynamic
library depending on which version of library it is compiled against. This
seems like a bad idea since there is no simple way of detection at run time
what the compile time options were used, and therefore which items from the
header are valid, given a dynamic lib binary.

My question would be why is it deemed necessary to conditionally include
functionality at all? Most libraries simply specify a minimum version
required for dependencies.

Having said that, if this is truly required, I guess an approach which
could work would be an "optional" tag, with a specific C macro check for
the C binding only, then bindings could note the optionality and handle it
gracefully if the optional method were not found in the library.

**Comment by jemc** [comment]
I agree with @twhittock that we should avoid this in zproject, and probably try to avoid it in CZMQ as well.

Regarding the conditional functions in CZMQ - perhaps we should move the conditional macros out of the headers and only have them in the private source files.

That is, if it's not possible to implement a given function in CZMQ because of the LIBZMQ version, we can make it return a sane static value or an error code where applicable.

**Comment by paddor** [comment]
Maybe this whole issue came a bit out of nowhere. This is what lead to this issue:

* I'm creating a high-level Ruby binding of CZMQ, based on the generated low-level Ruby bindings
* I want to support Z85 through `zarmour_*` functions
* there was no `api/zarmour.xml`, so I [added it](https://github.com/zeromq/czmq/compare/master...paddor:zarmour_api_xml?expand=1) (no PR yet)
* the `@interface` in `include/zarmour.h` now gets automatically generated
* I noticed a few differences, like missing enum constant values and their comments, missing `zarmour_print()` function, missing `#if` version guards
* most of those differences have been resolved by now, but one is still remaining: the `#if`
around the enum constant `ZARMOUR_MODE_Z85` (see [diff](https://gist.github.com/paddor/8e574f008970036705f1))

What are the options?

**Comment by jemc** [comment]
> most of those differences have been resolved by now, but one is still remaining: the `#if`
around the enum constant `ZARMOUR_MODE_Z85` (see [diff](https://gist.github.com/paddor/8e574f008970036705f1))

In this specific case, I think we can safely allow the Z85 enum value to always be defined, even when not implemented.  As long as the functions that take the enum value are implemented in such a way as to be safe if given the value (a quick look suggests that they are, but I didn't do a thorough review).

So in this case, I don't think the remaining difference is a problem.

Thanks for putting effort into repairing the rest of the diff, though.

**Comment by paddor** [comment]
Cool. In that case, I'll PR. Thanks. :-)
