### ISSUE TITLE
Problem: implicit enum values in API are not supported

### ISSUE THREAD

**Issue by paddor** [zeromq/zproject#309]
We're in the process of generating more of the C interfaces from the `api/*.xml` files. I noticed that when I define enum constants with implicit values (to resemble the original, hand-written C interface, see example [diff](https://gist.github.com/paddor/8e574f008970036705f1)), `./generate.sh` fails with the following error:

```
2015/11/22 22:38:51: gsl/4 M: Generating build scripts...
2015/11/22 22:38:51: (zproject_class.gsl 550) Undefined expression: value
```

**Comment by paddor** [comment]
Fixed this for the C generators and Ruby bindings:
https://github.com/zeromq/zproject/compare/master...paddor:implicit_enum_values_in_api?expand=1

**Comment by paddor** [comment]
@twhittock Could you fix the Python bindings? They're the next in line to expect all enum constants to be explicit.

Or is the better solution here to just always use explicit enum constants?

**Comment by paddor** [comment]
I just checked. The Ruby and the Python bindings are the only GSL scripts (next to the C generators), which respect enums from the APIs at all.

**Comment by jemc** [comment]
@paddor My only concern with implicit enum values is the possibility of being wrong about how they are assigned on some specific platform.  I'm not sure if you can actually rely on the assignment scheme, but I haven't researched it.

**Comment by twhittock** [comment]
Err yeah, let's not do it this way. It you don't want to specify values
explicitly in the model, then have a GSL script assign the values early in
the zproject transformation process, like other optional tags.

Having every binding implement the same logic to assign values is not
maintainable. Also, to throw a python phrase into the mix, "explicit is
better than implicit"

**Comment by paddor** [comment]
I don't mind explicit enum constant at all, it's just that the C interface of, e.g. the existing `zarmour.h` actually uses implicit enum constants. I guess it's safe to make those explicit.

I'll close this issue, then.
