### ISSUE TITLE
Problem: C interface generator skips excluded methods

### ISSUE THREAD

**Issue by paddor** [zeromq/zproject#310]
I'm talking about the methods defined in `api/*.xml`, which have the attribute `exclude = "1"`. I'd say those should still be present in a low-level, C interface.

Only binding generators should skip those methods (like printing details of object to standard output (`myclass_print()`) and maybe self tests (`myclass_test()`)).

Unfortunately, AFAIK, the code in `zproject_class_api.gsl` actually removes them from the data before the C generators are even called.

**Comment by jemc** [comment]
I'd say that there's no reason `print` and `test` shouldn't be included in bindings.  `print` can be especially useful in general, and `test` can be used to confirm everything is integrating correctly.

**Comment by sappo** [comment]
There's a set of default methods that is assumed for each class, e.g. print(). But not every class does implement these functions therefore they can be excluded in the api files.

**Comment by paddor** [comment]
@jemc Okay okay, it wouldn't hurt having access to those functions from a binding. True.

@sappo So if they're not supported by some particular class, why include them in the API XML at all? What's the actual reason for existence of the `exclude` attribute?

**Comment by sappo** [comment]
@paddor that's the right question. I guess it's good practice to have a print method and as most classes implement it may seemed logical to exclude them if not needed. Though I can see that this is confusing when writing api files. According to the CLASS style guide only one method must always be implemented namely the `test`-method.

**Comment by twhittock** [comment]
Exclude was added because these functions are assumed to exist by zproject.
We needed some way to tell the generators that they should *not* generate
such a method. It is only valid for the constructor, print and maybe one or
2 other methods.

**Comment by paddor** [comment]
@twhittock To me, it looks like it's valid for constructors, destructors, and all kinds of methods: https://github.com/zeromq/zproject/blob/master/zproject_class_api.gsl#L253-L262

Maybe this is a feature worth removing...

**Comment by jemc** [comment]
@paddor I remember the issue now that @twhittock explained it - if you give an empty class, zproject will fill it with some basic methods for convenience.  However, if your class doesn't need one or more of these "automatic"/default methods, you must mark them with `exclude=1`.  This means the method does not exist and is not implemented on purpose, so we shouldn't bind to it in any way.

I think that closes this issue, am I right?

**Comment by paddor** [comment]
@jemc I see it now in the code. It'd implicitly add a constructor, a destructor, a `print` method, and a `test` method, if any of those aren't already defined in the API.

I'll clarify the use of this attribute in the `api/myclass.xml` file though.
