### ISSUE TITLE
Problem: interrupt handling does not work

### ISSUE THREAD

**Issue by hintjens** [zeromq/zproject#381]
This is not strictly a zproject issue, but affects any binding of CZMQ.

CZMQ provides: (a) zsys_interrupted and (b) NULL on blocking recv methods and poll waits.

The problem today is CZMQ swallows SIGINTs yet does not expose (a) at least in any class.

Solution 1: by convention in bindings, disable CZMQ's interrupt handling. E.g. call 'zsys_set_handler (NULL);' in constructor for any class.

Solution 2: add new zsys class API to CZMQ. (This might also be a good time to split off the public zsys API from the private API used only by other CZMQ classes).

**Comment by Asmod4n** [comment]
:+1:

**Comment by jemc** [comment]
I think Solution 2 makes the most sense, if it fully solves the problem.  We should have an API model for zsys anyway.  Note that there is no zsys class instance, so they would all be singleton methods.

**Comment by hintjens** [comment]
Fixed by adding a zproc class in CZMQ that exposes the interrupt flag.
