### ISSUE TITLE
Problem: cmake build is broken

### ISSUE THREAD

**Issue by zoobab** [zeromq/zproject#400]
I am trying to compile with cmake. I did an "mkdir build && cd build && cmake ..", and got this error:

zoobab@chuchu /home/zoobab/soft/zproject [545]$ mkdir build
zoobab@chuchu /home/zoobab/soft/zproject [546]$ cd build/
zoobab@chuchu /home/zoobab/soft/zproject/build [547]$ cmake ..
-- The C compiler identification is GNU 4.9.3
-- The CXX compiler identification is GNU 4.9.3
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:21 (file):
  file STRINGS file "/home/zoobab/soft/zproject/include/myproject_library.h"
  cannot be read.

CMake Error at CMakeLists.txt:24 (message):
  failed to parse MYPROJECT_VERSION_MAJOR from myproject.h

-- Configuring incomplete, errors occurred!
See also "/home/zoobab/soft/zproject/build/CMakeFiles/CMakeOutput.log".

**Comment by sappo** [comment]
Actually there isn't anything to compile for zproject it only needs to be installed. Currently the only way to install zproject is using autotools as described in the README.
