### ISSUE TITLE
Problem: versioning is a mess (ABI version != software version)

### ISSUE THREAD

**Issue by hintjens** [zeromq/zproject#409]
The version check on Linux uses the ABI version, which is NOT the same as the product version.

E.g. libzmq 4.1 has ABI version 5:0:0.

This causes errors in autoconf configure, e.g. "I need CZMQ 3.0.1" translates to "I want ABI version 3:0:1" which means libczmq.so.3.0.1. And since CZMQ exports ABI version 3:0:0, the so is libczmq.so.3.0.0.

zproject_autoconf.gsl futzes this by setting the ABI version to major.minor.0, which does not work.

Hacky unacceptable workaround: force ABI version to product version. I'm going to veto this for the simple reason it will not work with libzmq. Also it's wrong.

Short workaround: remove all version checks in zproject_known_projects.gsl.

Proper workaround: allow projects to specify their ABI version explicitly, and default to 0:0:0 not the product version; and find another way to do the version check in autoconf.

**Comment by jemc** [comment]
For previous discussion on this, see: https://github.com/zeromq/zproject/issues/86#issuecomment-63434589

**Comment by hintjens** [comment]
Good catch. It still doesn't work though, e.g. Libzmq 4.2 uses abi 5:0:0...

**Comment by bluca** [comment]
For the version check IMHO we should just rely on pkgconfig, it's the only sane way. ABI check is really not necessary since we are rebuilding anyway, only the version is important.
