### ISSUE TITLE
Problem: zproject generates too much :)

### ISSUE THREAD

**Issue by hintjens** [zeromq/zproject#458]
We have a problem of luxury; the default is to generate *everything* and for new users this is a bit overwhelming.

I'd like to refactor the backends a little so that there's more structure to them. This means every backend should be a function with a consistent name, e.g. "target_xyx" as GSL lets us call functions with constructed names. We can then generate a core set of backends by default, and the others on demand, when the user adds "<target name = "xyz" />" into their project.xml.

Solution: generate core targets by default, and others on demand only.

**Comment by sappo** [comment]
This sounds like an excellent solution :+1:

**Comment by hintjens** [comment]
Fixed.
