### ISSUE TITLE
Array/list types support

### ISSUE THREAD

**Issue by emef** [zeromq/zproject#461]
Perhaps it's just undocumented, but I don't see support for array types.

**Comment by paddor** [comment]
I think you'd use a pointer in that case.

**Comment by sappo** [comment]
Or use zlist/x.
Am 18.01.2016 7:33 nachm. schrieb "Patrik Wenger" <notifications@github.com

**Comment by hintjens** [comment]
Array of what, and what's the use case? I'm closing this issue as speculative.

**Comment by emef** [comment]
I'd like to define a constructor that takes a float* or double* e.g.

```xml
  <constructor>
    <argument name = "data" type = "float*" />
  </constructor>
```

When I run generate.sh with this (and permutations) it just ends up adding underscores to the type name but never ends up doing what I want. Is this supported and I'm just missing it?

**Comment by emef** [comment]
I found c_type but I guess that's just not portable to other languages?

**Comment by paddor** [comment]
If you really need to pass a pointer to a double, I think you could use `ny_reference = "1"`. But it still seems weird. Please explain your usecase.

You might wanna take a second look at [CLASS](http://rfc.zeromq.org/spec:21).

**Comment by hintjens** [comment]
Matt, perhaps it's worth reading what I've already written on scalablec.org.

We try hard to avoid weirdness in the APIs. Constructors should normally be
void unless there is an excellent reason for passing data.

I understand you want to pass an array of values. Yet if you explain your
use case rather than ask for specific possibilities, we can help you better.

One pattern for passing an array of values is the zpoller constructor, see
how it works.

However I suspect in your case the answer lies elsewhere.

**Comment by emef** [comment]
I am building a distributed dataset engine, similar to apache spark but much more limited in scope. There will be many workers across machines that will each own "blocks" of the original data. A session might go something like:

1. driver calls load("path1,path2,...,pathn")
2. paths get mapped to block descriptors (id, location, offset, length)
3. descriptors get sent down PUSH socket to workers
4. workers PULL the block descriptor and load the data into memory
5. the block data (float*) should be stored in a memory manager (map block_id -> data)
etc.

The constructor definition that started this discussion is the one that holds the raw block data and some metadata. 

Do you recommend generating headers for all classes, including internal ones such as this? I could leave off the api xml definition and write the header myself, I was just trying to embrace the zproject way.

**Comment by hintjens** [comment]
You don't need to use the API modeling for internal classes; it is
essential only when you start generating bindings. It's the binding
generators that set limits on how complex the data types can be.

Using a class and header is great, for internal classes, and you would
simply write them by hand. Put internal class headers in src and include
them in xxx_classes.h, so they're available to other classes.

-Pieter

**Comment by emef** [comment]
Ok I appreciate the response, I suppose I went overboard trying to use the API modeling for all my classes. It really does provide a nice way to spec out components and document classes/methods/arguments all in one place.

**Comment by hintjens** [comment]
What you can always do is take the API model and write your own code
generator for it, it's not as much work as you'd imagine and it will teach
you a lot. You could take zproject_class_api.gsl as example.

**Comment by emef** [comment]
I'll take a look, could be fun. Thanks
