### ISSUE TITLE
Problem: Draft classes are not available when installed

### ISSUE THREAD

**Issue by sappo** [zeromq/zproject#465]
In case of czmq this issue occurs for ztrie and zproc. They will be available if the define WITH_DRAFTS is set in the platform.h which is only included in the private header. Thus applications that include the public header e.g. czmq.h won't be able to use draft apis.

**Comment by hintjens** [comment]
OK, fixing this. In fact the public header should define all draft
APIs as before, they just won't be built and exported by the library
unless WITH_DRAFTS is defined when it's built.

**Comment by sappo** [comment]
Shouldn't they be build and exported by the library unless it's not the git master?

**Comment by hintjens** [comment]
That's harder to detect. Detecting .git is simple and separates our main use cases, tarballs vs. git repo.

If someone is building from specific tags then IMO they can configure this by hand.

**Comment by sappo** [comment]
Agreed!

**Comment by sappo** [comment]
You're fix #466 doesn't work entirely. The draft classes are included now but the draft methods still have the WITH_DRAFTS define which is not available when installed.

**Comment by bluca** [comment]
I have an alternative solution in mind.

What about using pkg-config? It's quite common for libraries to set CFLAGS needed to build in pkg-config. Then if we build from master the pkg-config file can include WITH_DRAFTS as a define, else it won't.

Thoughts?

**Comment by sappo** [comment]
Sounds easy enough. When is the define applied? During configure?

**Comment by bluca** [comment]
Yep! PR coming up shortly.

**Comment by sappo** [comment]
If this works we could revert 403d5f3!?

**Comment by bluca** [comment]
In the PR I'm about to send I'll revert that not so much for the headers include (as a user, I think it's much clearer if the includes are behind the \#ifdef too, but I'm not religious about that), but for the constants and the typedefs. I think those should definitely be behind the \#ifdef as otherwise they will be in the stable .so, and as we know perfectly well if something is available it will be used :-)

**Comment by bluca** [comment]
Opened https://github.com/zeromq/czmq/pull/1311 to regenerate CZMQ and fix the regression (should have thought about this issue, sorry about that)

**Comment by sappo** [comment]
Don't worry, it works great now :+1:
