### ISSUE TITLE
Problem: malamute executables now fail to build

### ISSUE THREAD

**Issue by asokoloski** [zeromq/zproject#468]
https://github.com/zeromq/malamute

I think that the problem is that pkg-config method of specifying "-DWITH_DRAFTS=1" only works once the library is already installed.  If the project includes executables that use draft classes like malamute does, they don't get the flag and can't find the symbols they need.

That's as far as I can tell, unless I'm totally confused.

      CC       src/src_malamute-malamute.o
    src/malamute.c: In function ‘main’:
    src/malamute.c:109:36: error: ‘mlm_server’ undeclared (first use in this function)
         zactor_t *server = zactor_new (mlm_server, "Malamute");
                                        ^
    src/malamute.c:109:36: note: each undeclared identifier is reported only once for each function it appears in
    Makefile:1059: recipe for target 'src/src_malamute-malamute.o' failed

I think I have an idea of how to fix this, but I have little knowledge of best practices for building c projects.  Would it be a good idea to rename pkg_config_defines to something that is not pkg-config specific, and then use that both for setting Cflags in libmlm.pc.in and also passing into the build commands for any executables in the project?

**Comment by bluca** [comment]
Hi,

The CI (after a few fixes that I'm going to push shortly) seems to work just fine:

https://travis-ci.org/bluca/malamute/builds/103453980

Also isn't that compile error about "mlm_server" rather than a library function?

**Comment by asokoloski** [comment]
Yes, mlm_server is a zactor_fn declared in mlm_server.h, so that needs to be included, right?  Sorry, I'm not very proficient in C and may be using the wrong terms.

What happens for me is, when compiling mlm_library.h as included by malamute.h, WITH_DRAFTS is not defined.  I tried to trace it back and I can see

    pkg_config_defines = -DWITH_DRAFTS=1

in the Makefile, but pkg_config_defines is actually not used anywhere in my Makefile.

**Comment by asokoloski** [comment]
Ok, I'm starting to get an idea.  It seems like this line in configure.ac:

    AC_DEFINE(WITH_DRAFTS, 1, [Build and install draft classes and methods.])
is not effective for some reason -- my Makefile says

    DEFS = -DHAVE_CONFIG_H

when it should also have -DWITH_DRAFTS=1

**Comment by asokoloski** [comment]
AH!  Yes, DEFS doesn't have the option because of 

    AC_CONFIG_HEADERS([src/platform.h])

I'm trying to learn autoconf as I go... :|  So what's happening is these executables don't get WITH_DRAFTS because they don't import platform.h.

Anyway, it seems like there are multiple possible solutions that I can think of:

1) Have the relevant source files for executables import platform.h before importing malamute.h.
2) define WITH_DRAFTS explicitly in each of them before importing malamute.h
3) change zproject to somehow pass this option through so that executables get WITH_DRAFTS enabled automatically when appropriate (building from git repo).

These all seem a bit off, because these executables would then be broken when building from a tarball, right?  Maybe the way to go is to mark the <main> as having state="draft" or state="stable" as well?  That way, if they depend on anything with state="draft" then they must be marked state="draft" as well, and would just not be built for a stable release as they wouldn't work anyway.

**Comment by bluca** [comment]
Ah, the joys of Autotools!

Commit 04097c7f0d13510a6fa401adfec6d0c0cf751704 solved that issue, and platform.h is included by default. Is your local tree up to date with Github? Also, have you regenerated autotools by rerunning ./autogen.sh and ./configure ?

**Comment by hintjens** [comment]
Please take the latest git master, then re-run ./autogen.sh && ./configure
and then make should work.

**Comment by asokoloski** [comment]
I'm completely up to date (at 57aa0e2e4374b) -- I've even run gsl project.xml on malamute.

After running ./autogen.sh  ./configure, I ran

V=1 make

gives this error:

gcc -DHAVE_CONFIG_H -I. -I./src     -I./include -pedantic -Werror -Wall -Wc++-compat -D_GNU_SOURCE -DLINUX -D_REENTRANT -D_THREAD_SAFE  -Werror=format-security -g -O2 -MT src/src_malamute-malamute.o -MD -MP -MF src/.deps/src_malamute-malamute.Tpo -c -o src/src_malamute-malamute.o `test -f 'src/malamute.c' || echo './'`src/malamute.c
src/malamute.c: In function ‘main’:
src/malamute.c:109:36: error: ‘mlm_server’ undeclared (first use in this function)
     zactor_t *server = zactor_new (mlm_server, "Malamute");

Does make run the same command for you to compile src/malamute.c?  Is it supposed to have a flag for WITH_DRAFTS?

It looks like the problem is related to this change you made on monday, Pieter.

    commit 916a7e0cff5ffc5a4e53aa3603bb3cd0eb4a38d7
    Author: Pieter Hintjens <ph@imatix.com>
    Date:   Mon Nov 9 18:41:41 2015 +0100
    
        Problem: Malamute main does not build outside project
    
        Which is a shame as it's useful to provide an example of
        calling the server.
    
        Solution: use <malamute.h> instead of "mlm_classes.h"

mlm_classes.h, which is private, includes platform.h, while the public malamute.h header, does not.  It's not supposed to, as that would pollute the namespace of external code, right?  But that means that when compiling malamute.c, mlm_library.h needs some other way of getting WITH_DRAFTS defined.

So Luca's change to add CFLAGS via pkg-config makes all that work, for external executables that are being built after the project (in this case, malamute) has been installed.  But that doesn't include the malamute binary, because malamute hasn't been installed yet.

How is it supposed to work, anyway?  I can only guess that you guys have some state on your systems that I don't...

**Comment by hintjens** [comment]
Yup, I think my change was a rare "this will break code in two months'
time" change.

I've reverted it and sent a PR.

**Comment by asokoloski** [comment]
Heh, glad I could help from over here two months in the future :)

Other executables were still broken so I also made them use "mlm_classes.h" and sent a pull request to malamute.

**Comment by hintjens** [comment]
Merged, and I saw Travis is happy again. Yay! :)

**Comment by bluca** [comment]
:+1:
