### ISSUE TITLE
Problem: mkapi.py has inconsistent license & blurb

### ISSUE THREAD

**Issue by hintjens** [zeromq/zproject#477]
@vyskocilm is it OK with you if I use our standard header (MPLv2 + copyrights)?

**Comment by vyskocilm** [comment]
Yes, definitely!

**Comment by hintjens** [comment]
OK, thanks. I'll do that. I'm using and documenting mkapi.py, hitting an error that I'll log now.

**Comment by vyskocilm** [comment]
Ok, please cc me for all issues you will hit.
