### ISSUE TITLE
Problem: mkapi.py says "TypeError: 'NoneType' object is not iterable"

### ISSUE THREAD

**Issue by hintjens** [zeromq/zproject#478]
To reproduce:

```
git clone https://github.com/scalable-c/globdom
cd globdom
mkapi.py globdom.h gdom_client
```

**Comment by hintjens** [comment]
@vyskocilm cc :)

**Comment by hintjens** [comment]
Ah, I was unable to figure it out. Maybe an example of the command line would be useful, if one runs it without arguments. In the end I just wrote my API file by hand, it was easier :)

**Comment by vyskocilm** [comment]
@hintjens  actually there NoneType bug was due the fact tool did not worked w/o --include parametr. If it will work, you'll hit the pycparser error, so you will create an issue anyway :)

I did it slightly more user friendly, as I was hit by recently added draft methods too
BTW: command line was https://github.com/zeromq/zproject/pull/480

I'll update the README of zproject

**Comment by vyskocilm** [comment]
BTW: thanks for trying the tool anyway, it's good to know that at least a few people try to run it :)
