### ISSUE TITLE
Problem: use.implied/optional mean what?

### ISSUE THREAD

**Issue by hintjens** [zeromq/zproject#525]
It's undocumented what "implied" means, and only a few targets use it. 

Also what does "optional" mean? 

E.g. we have this in known_projects:

    <use project = "libzmq" prefix = "zmq"
        repository = "https://github.com/zeromq/libzmq"
        test = "zmq_init">
        <use project = "libsodium" optional = "1" implied = "1" />
    </use>

Which breaks Windows, without clear guidelines as to what optional and implied mean in this case.

I'm going to assume 'optional' means look for project any way possible, define HAVE_XXX macro if it is installed, and link with it, else not.

Solution: I'm going to assume 'implied' means nothing at all, and start removing it from the few places it exists, unless someone raises a hand.

**Comment by hintjens** [comment]
So `use.implied` is calculated, and must not be specified in the project model.  It is not documented in the known projects file. It means, at least, that the project API (header) is provided by another project API.

The android target uses the implied property, with a recursive build. Afaics no other targets do this.

**Comment by bluca** [comment]
If I remember correctly, implied was used in Android because a lot of C libraries are built into bionic (android's libc), so there are no .so to link against. pthread and uuid were examples if I can recall.

**Comment by hintjens** [comment]
Further, e.g. libuuid and libsodium are both 'optional' and yet it means very different things.

**Comment by hintjens** [comment]
Also there is overlap/redundancy between e.g. the definition of czmq in zproject_known_projects.xml and its definition in czmq/projects.xml. This is fixable via #395.

**Comment by hintjens** [comment]
Maybe we can think about what we actually need in the model for each project:

I'm going to close this vague issue and start a new one...

**Comment by jemc** [comment]
@hintjens - an `implied` dependency is one that must be present to compile, [but is not `#include`d in the C source](https://github.com/zeromq/zproject/blob/a52c00c1f090bbdbb89db1293fe8554fd92e9e22/zproject_class.gsl#L60-L69).  As you already found, these are generated from known projects.
