### ISSUE TITLE
Problem: systemd integration is slightly broken

### ISSUE THREAD

**Issue by lerwys** [zeromq/zproject#546]
Problem: In Malamute project, systemd integration is slightly broken. Project Malamute (commit c7301f4) currently has these problems.

1. The config file .cfg (malamute.cfg, for instance) is only being installed when `--with-systemd` option is selected in ./configure. This should be installed regardless, I think.
2. ./configure --help lists systemd as` --with-systemd-units`, but this does not exist and gives me an error (unrecognized option) as the correct option is `--with-systemd`.

I think I could prepare a patch to fix those if they are indeed errors.

**Comment by bluca** [comment]
Regarding 2, I changed to with-systemd-units inhttps://github.com/zeromq/zproject/commit/6cf938d8f5fb30761a101ae1552dae0eedc887d4 because with-systemd is ambiguous and confusing, given that target only adds the invite files. Other systemd integration are possible, like using libsystemd, and a user might want one but not the other.

Is Malamute up to date with latest zproject? If so, have you regenerated the autoconf stuff from scratch?

**Comment by lerwys** [comment]
That's nice. I think it's good to have different systemd integration options as you mentioned.

Regarding the problem. I rechecked my zproject local repository and it was in sync with upstream. Then I tried to regenerate autotools config files with `gsl -target:autotools project.xml` and nothing changed. I also tried to do a fresh malamute clone and do`./autogen.sh && ./configure --with-systemd-units`, but the problem persists. I'm getting the following warning:

` configure: WARNING: unrecognized options: --with-systemd-units`

Maybe I'm missing something here?

**Comment by bluca** [comment]
No you are right, there is a problem in the autoconf file now that I look at it closely, it's my oversight, sorry about that.
PR coming to fix it.

**Comment by lerwys** [comment]
Thanks Luca. 

About the first issue 

"The config file .cfg (malamute.cfg, for instance) is only being installed when --with-systemd option is selected in ./configure. This should be installed regardless, I think."

What do you think? I see that on previous zproject commits this was the case, but it was changed recently to only install .cfg files when selecting --with-systemd.

**Comment by bluca** [comment]
Yes that sounds wrong. Would you send a PR to fix it?

**Comment by lerwys** [comment]
Sure. Right away. =]

**Comment by bluca** [comment]
Thanks!

Is it all working now?

**Comment by lerwys** [comment]
You're welcome!

At least for Malamute, I'm able to run ./configure without --with-systemd-units and malamute.cfg file is installed anyway.

**Comment by bluca** [comment]
Awesome! I'll close this issue then. Thanks for reporting and taking the time to fix it.

**Comment by lerwys** [comment]
Ok, No problem. Just small contributions to great projects! =]
