### ISSUE TITLE
Problem: --without-xyz does not work

### ISSUE THREAD

**Issue by hintjens** [zeromq/zproject#567]
I was wondering why `--without-uuid` refused to work in CZMQ. Finally I ripped the dependency out, as it's entirely pointless (to generate 32 random bytes does _not_ need an external, non-portable, eternally different library). 

However, note this code in `zproject_autotools.gsl`:

```
        AC_ARG_WITH([$(use.libname)],
            [
                AS_HELP_STRING([--with-$(use.libname)],
                [Specify $(use.libname) prefix])
            ],
            [search_$(use.libname)="yes"],
            [])
```

Now, the `--with` option in autoconf is conventionally used to select/deselect an optional package. It is _not_ used to specify the prefix for a package.

We should not be creating surprises for the user.

**Comment by jimklimov** [comment]
I'm digging in this area of code for the past few days, and it seems that the de-facto syntax is to indeed enable/disable search for an optional package. However the argument can also take a value (beside implicit "yes" or the currently ignored "no"), which is then treated as the path such as a source code build workspace, under which there are an `include/` and `lib/` subdirectories containing the necessary files of this dependency.

I'm not triaging several ways to reorganize this code, hopefully will come up with a PR soon.

**Comment by jimklimov** [comment]
With PR #838 in place, the `--without-stuff` works as well as `--with-stuff=no`, so the specific scope of this issue is solved.
