### ISSUE TITLE
Problem: how to selectively ignore case for project dependency names

### ISSUE THREAD

**Issue by chaicko** [zeromq/zproject#654]
Hello all, 

I am starting a new project based on CZMQ and want to use zproject to structure it. I have a dependency on a JSON library called [cJSON](https://github.com/DaveGamble/cJSON).

On my `project.xml` I added the dependency like this:
```xml
<use project = "cJSON" prefix = "cJSON" libname = "libcJSON"
     header = "cJSON/cJSON.h"
     repository = "https://github.com/DaveGamble/cJSON.git"
     test = "cJSON_test" />
```
As you can see, the project has mixed case names for headers, library target, etc. 

When generating the project with `gsl` I found that all references to this dependency are set to lower case and thus the library is not found when configuring the project. For example, the cmake find script is named `Findcjson.cmake` instead of `FindcJSON.cmake`, the included header is named `cjson/cjson.h` instead of `cJSON/cJSON.h`, etc.

I read in the gsl doc that you can configure it to not ignore case with the `ignorecase=0` option. I tried this by running `gsl -ignorecase:0 project.xml` but got an error when processing actors definitions:
```
chaicko@gauss:~/shkcomm$ gsl -ignorecase:0 project.xml 
GSL/4.1c Copyright (c) 1996-2016 iMatix Corporation
gsl/4 I: Processing project.xml...
...
(zproject_skeletons.gsl 85) Undefined expression: ACTOR
```

So globally changing the option does not work. Then I tried to modify the `zproject_projects.gsl` script somehow but couldn't make it work (I am rather new to gsl scripting and the tool in general).

Obviously I can fix the generated files manually, but would like to make zproject work for me instead.

So the question is how can I configure the `ignorecase` option on a per-tag basis? Is it possible to do it without modifying zproject's gsl scripts?

Thank you for your time!

**Comment by hintjens** [comment]
Names are normalised in the various scripts, to produce valid filenames.
You'd have to find and fix all these cases. I'd really advise accepting the
current style for filenames etc. even if the project has different
capitalisation. E. g. CZMQ vs. czmq.

**Comment by sappo** [comment]
If you need a json library that works out of the box with zproject use
jansson (https://github.com/akheron/jansson).

zproject already knows this library so you can include it like you do czmq
or zyre.

2016-07-11 22:05 GMT+02:00 Pieter Hintjens <notifications@github.com>:

> Names are normalised in the various scripts, to produce valid filenames.
> You'd have to find and fix all these cases. I'd really advise accepting the
> current style for filenames etc. even if the project has different
> capitalisation. E. g. CZMQ vs. czmq.
> On 11 Jul 2016 9:57 pm, "Alejandro Javier Schwoykoski" <

**Comment by hintjens** [comment]
To expand on what I said, it is usually a Bad Idea to capitalize library names or file names in any way. E.g. people expect to install `libczmq.a` and not `libCZMQ.a`. The use of rANdoM cASe creates surprise, and scope for errors. zproject deliberately forces filenames to lowercase except when external systems already use mixed case. It's bad enough in code. Using names like `CMakeLists.txt` externally is just rude IMO; it forces internal conventions on the world.

So please stick to lowercase, make your `libjson` or chose another project name that works... 

That is my strong advice.

**Comment by chaicko** [comment]
@sappo The project I'm working on is an embeddable network server for an existing embedded Linux target. It is supposed to be integrated into an existing application on the target. Unfortunately the toolchain is rather old (gcc 4.3.5 with uclibc) and jansson fails to compile for it. Also the existing application is already using cJSON so I picked it for ease of integration, although I prefer jansson for sure.

@hintjens I agree with you on the library names, but in this case the external dependency project does not adhere to the rule. I can either ask the cJSON maintainer to change the name (non feasible), fork it and change it in my own fork or change the dependent project to accept the weird names. I ended up just doing the latter: added a post zproject generation script that just fixes all the names in the generated files (just the well known `grep -rl | xargs sed -i` recipe). It is enough for this simple issue.

Thank you for your suggestions.

Should I close this issue?

**Comment by hintjens** [comment]
Ah, I misunderstood.

OK, so in that case find all places the library filename is generated wrongly. Find the original places in the scripts, and use this syntax: `$(filename:)` instead of `$(filename)`. You have to control this instance by instance, not using a global setting (or everything breaks). You can see the GSL docs for all possible case conversion modifiers. ':' seems best.

**Comment by chaicko** [comment]
Thanks!
