### ISSUE TITLE
Problem: building projects of ZeroMQ ecosystem takes long with Travis CI

### ISSUE THREAD

**Issue by jimklimov** [zeromq/zproject#734]
Context: With the dynamic approach of different ZeroMQ-related projects, where the Git HEAD of each dependency should always be used to take advantage of latest features (and tested against, in case of CI), there is a problem that Travis CI spends the first couple of minutes just building required dependencies, such as gsl, libzmq, czmq, etc. If project merges are fast, often the PR git branch is no longer there by the time Travis gets to trying to pull and compile it.

Solution: When the GitHub'ed upstream/master of a zeromq ecosystem project (and optionally of projects driven by zproject) is updated and by itself has a TravisCI integration and passes the tests sucessfully, it should also produce packages in format supported by TravisCI hosts (e.g. `*.deb`, `*.dmg` - maybe using https://github.com/jordansissel/fpm for unified packaging, maybe not) and use the Travis `deploy` action to upload them to GitHub as a release (maybe a rolling `latest` release with a continuously overwritten couple of files for the package and for its source git metadata and checksums) : https://docs.travis-ci.com/user/deployment/releases

Then the steps which `git clone ... make install` the upstream projects can first look for the package to be available and have same commit-id as the Git HEAD, and if a suitable package is available - just install it quickly (if any step of the check or install fails - build it locally as before).

The purpose of this issue is to ask for common-sense review - is this a reasonable way to go? Would the ZeroMQ upstreams pick up this approach to provide such prebuilt packages of themselves so the subsequently regenerated zproject-driven projects can benefit? Is there some inherent stupidity in the plan above that would make it explode? Should I or someone else spend time implementing this? Please be constructive though :)

Note; The links above came from https://github.com/theory/sqitch/issues/283 "Use Travis CI to create and publish packages to GitHub and/or upstream/private repositories". For DEBs they also suggested https://help.launchpad.net/Packaging/PPA hosting.

**Comment by bluca** [comment]
We already build a lot of the packages on each merge/push:

https://build.opensuse.org/project/show/home:zeromq:git-stable
https://build.opensuse.org/project/show/home:zeromq:git-draft

The problem especially on Travis is that you need to whitelist repositories to be able to use them with apt-get. Installing packages manually after a wget is of course possible, but a bit of a pain to handle due to dependencies etc

**Comment by jimklimov** [comment]
I do not think that `wget ... ; dpkg -i ...` is much worse regarding dependencies than `git clone ... config... make` ;) At least, I do not expect an everyday unprivileged `configure` script to go install packages.

Although this comment has a consequence: maybe we should not build packages, but just tarball the build (install) area for such subprojects? Anyhow the limited use-case is to carry the binaries over from one Travis instance to another...

**Comment by bluca** [comment]
On Linux, if pre-built binaries are to be used, I would rather use OBS, as that makes it safe with regards to dependencies and ABI compatibility (eg: zyre uses czmq which uses libzmq, then we must ensure that the czmq is always rebuilt after zmq). We do not want to get into the business of manually checking and ensuring ABI compatibility :-)

The issue on Travis is that, in order to use the faster container-based infrastructure, there is no sudo access, so no dpkg -i. To have sudo you need to use the older, slower VM-based infrastructure. But then any gain from pre-built binary packages is lost and then some. Especially on queue times, which is what is really the problem, the container based infra is so much faster.

**Comment by jimklimov** [comment]
Ok, thanks for the valuable input. I guess the implementation of
improvement should consider the following points then:

1) aim lower in the food chain - publish a tarball with the workspace
(including git metadata, possibly switched into a private branch like
'lastbuild') that passed 'make check'. Maybe also integrate with ccache (if
available in travis) and tarball the private cache dir (with just objects
from this project) to speed up possible later rebuilds.

2) Probably the tarball name can include the (hash of?) compiler and/or
settings, so a tested build can pick the right tarball if available - or
skip this speedup.

3) The runtime travis test on a successful improved codepath can then
download such tarball, ensure that 'git remote upstream' in the un-tarred
workspace is set where this currently tested project intends with its
ci_build.sh, and fetches the respective branch (defaults refer to github
upstream/master).

3.1) If `git diff` of the fetched master and available `lastbuild` shows no
differences, then the code is still up-to-date.

3.2) Otherwise 'git clean -fdx; git checkout -f' the workspace and merge
with the fetched master (or just check it out and re-merge with tracked
copy of upstream/master to be sure), and do the usual
autogen+configure+make. If ccache is available, unchanged sources (text
after cpp processing) quickly produce same binaries from cache; progs/libs
are re-linked.

4) Same as before if tarball was not available - git clone, autogen, conf,
make. Probably the ccache can be skipped then.

5) With either freshly built, or older up-to-date, workspace, a travis
local 'make install' will quickly put the binaries where expected.

This way we have benefits for builds that are same as in tarball (instant
'make install') or differ from it negligibly (most source in ccache still
matches). Completely freshly cloned builds may suffer some additional
latency from checks for presence of the tarball though (timeout to see it
is missing). Not-updated projects do not have this codepath and only suffer
full rebuilds as now.

Something like that ... makes sense?

//Jim Klimov

--
Typos courtesy of GMail on my Samsung Android

08.12.2016 16:36 пользователь "Luca Boccassi" <notifications@github.com>
написал:

**Comment by bluca** [comment]
Mmh I'm still not convinced it's necessary, nor desirable, to reinvent our own binary delivery system. It's just a huge overhead for a problem that had been solved for years.

Thinking about it, the exact same result can be achieved, when root is not available, by simply downloading and extracting the packages built on OBS:

wget foo.deb
dpkg -x foo.deb ./local/path

The changes to the scripts should be minimal, just swapping the git clones and builds with the above.

But even before that, the very first thing to try is the GCE based trusty build with sudo, by setting the parameter in the travis.yml, and compare results with the container based build time

**Comment by jimklimov** [comment]
Just in case, does the OBS build in travis environments (real travis, or a setup with same versions) - will ABIs etc. not be violated?

**Comment by jimklimov** [comment]
Anyhow, times do vary in measurements making the tests rather uncertain. Still, the order of magnitude holds - 2-3 minutes for a simple projects with czmq, libzmq, malamute and zyre compiled as prerequisites (non-root containers). As of latest run in my test repo and cloud travis:

* libzmq:
** autogen - 9 sec
** configure - 5 sec
** make -j4 - 66 sec
** make install - 0.6 sec

* czmq
** autogen - 7 sec
** configure - 3 sec
** make -j4 - 7 sec
** make install - 0.2 sec

* malamute
** autogen - 7 sec
** configure - 3 sec
** make -j4 - 2.6 sec
** make install - 0.2 sec

* zyre
** autogen - 7 sec
** configure - 3 sec
** make -j4 - 2.2 sec
** make install - 0.2 sec

So, the single greatest "offender" is the build of libzmq (C++, man); the greatest systematic offender is autogen, and configure (at least on some systems).

**Comment by bluca** [comment]
OBS will always have the latest version of all packages, always automatically rebuilt against the latest versions of all dependencies, so it's the safest thing.

Those are interesting measurements, I kinda assumed libzmq would be the slowest.

Next you could try to set in .travis.yml:

```
sudo: required
dist: trusty
```

And see what difference that makes.

I'm preparing a libzmq build on OBS, I noticed we didn't have it set up for Ubuntu 14.04. Since it's LTS we should have it anyway.

**Comment by bluca** [comment]
libzmq Ubuntu 14.04 build should become available at

http://download.opensuse.org/repositories/home:/zeromq:/git-stable/xUbuntu_14.04/

once this is merged: https://github.com/zeromq/libzmq/pull/2247

**Comment by jimklimov** [comment]
Hm... there is also Travis caching - https://docs.travis-ci.com/user/caching/
I wonder if it can solve the issue instead, at least build-once-per-project would be a good boost...

**Comment by jimklimov** [comment]
It seems that valgrind tests "natively" require a fully privileged VM, this sub-job takes about 32 sec longer to start the build. Otherwise timing of steps inside is about the same or negligibly faster (so overall the overhead loses, as long as we do complete builds of prereqs in both cases):

* libzmq:
** autogen - 9 sec
** configure - 5 sec
** make -j4 - 58 sec
** make install - 0.4 sec

* czmq
** autogen - 7 sec
** configure - 3 sec
** make -j4 - 7 sec
** make install - 0.2 sec

* malamute
** autogen - 7 sec
** configure - 3 sec
** make -j4 - 2.4 sec
** make install - 0.2 sec

* zyre
** autogen - 7 sec
** configure - 2 sec
** make -j4 - 2.1 sec
** make install - 0.2 sec

**Comment by jimklimov** [comment]
BTW, According to https://travis-ci.org/eaton-bob/joex/jobs/182696537 there is a ccache in travis environment, so we can use it (along with any sort of stashing the build workspaces - or just the common `~/.ccache` dir if we go the Travis-caching way on a per-project basis rather than spread out centralized artifacts) to speed up subsequent rebuilds even if all other script code remains the same.

**Comment by bluca** [comment]
ccache is another good option, yes.

packages are now available: http://download.opensuse.org/repositories/home:/zeromq:/git-stable/xUbuntu_14.04/

**Comment by bluca** [comment]
If you want to test and time it, these are the changes needed for the build:

https://github.com/bluca/czmq/commit/51cd860fc3b3332901d0abfae5dd0abc6c58554c

**Comment by bluca** [comment]
CZMQ and ZYRE packages available as well now. Malamute is failing to build, I'll try to have a look tomorrow.

**Comment by bluca** [comment]
Malamute packages for Ubuntu 14.04 are now available as well.

**Comment by bluca** [comment]
gsl, zproject, zproto, libzmq, czmq, zyre and malamute packages are now available for Ubuntu 12.04 too.

A cmake zyre build now takes 36 seconds :-) And it's binary-equivalent to the previous one where it was rebuilding everything

Apart from regenerating the scripts from zproject, the only thing you need is something along these lines in your .travis.yml:

```
addons:
  apt:
    sources:
    - sourceline: 'deb http://download.opensuse.org/repositories/home:/zeromq:/git-draft/xUbuntu_12.04/ ./'
      key_url: 'http://download.opensuse.org/repositories/home:/zeromq:/git-draft/xUbuntu_12.04/Release.key'
    packages:
    - malamute
    - zyre
```

Add zproject as well if you run the check_zproject CI test.

Are this and the work you did to add support for ccache enough to close this bug?

**Comment by bluca** [comment]
Note that you can also use the git-stable repository instead of the git-draft, if you don't use DRAFT APIs from the dependencies

**Comment by bluca** [comment]
Finally, using the external repo works also in the container-based CI run, which is the fastest one, so no need to switch to the Trusty build as I originally said.
I thought the apt addon wasn't supported on the precise container, but either I was wrong or they fixed it recently, either way it's all good now

**Comment by jimklimov** [comment]
Thanks for the research and results :)

Yes, I believe these approaches should solve the slow-test issue... at
least its technological side is now clear and fixable; a nice icing on the
cake could be to add such links to the travis.yml via zproject, perhaps as
optional parameters in project.xml (whether to use packages or new
rebuilds, and also mention the draft vs. non-draft desires as a separate
toggle, which could/should also influence settings for the always-rebuild
mode).

I think the "stached ccache" integration still has its own merits even with
packaged pre-requisites, to speed up rebuilds of the tested project itself
and/or of not-known_project (or not-packaged) dependencies.

2016-12-29 18:50 GMT+01:00 Luca Boccassi <notifications@github.com>:

**Comment by bluca** [comment]
Yes having both ccache + packages is very nice, they both help in different situations.

The travis.yml generated by zproject already adds the links to the repository, I've implemented that too.

**Comment by bluca** [comment]
Closing this since we got a nice working solution with ccache + prebuilt packages
