### ISSUE TITLE
Problem: license of generated sources not explicitly stated in README

### ISSUE THREAD

**Issue by bluca** [zeromq/zproject#773]
Given the very first step when creating a new zproject-based project is to defined your own license.xml file, it seems obvious to me that the intention is for the user of zproject's templates to decide the license of their project, including the sources and bindings generated by zproject.

I'd like to add a line to the README under the ownership and license section to clarify this so that there can be no doubt (lawyers being lawyers)

@sappo  @vyskocilm @jemc @jimklimov @twhittock (to cite a few of the contribs as listed by github), any comment on this?

**Comment by vyskocilm** [comment]
Sounds reasonable to me

Dne 1. 1. 2017 11:58 napsal uživatel "Luca Boccassi" <
notifications@github.com>:

**Comment by jimklimov** [comment]
Good idea, and maybe clarify about use of license.xml as a way to seed
license headers in generated files.

2017-01-01 11:58 GMT+01:00 Luca Boccassi <notifications@github.com>:

**Comment by jemc** [comment]
Yes, I agree that the intention is for the generated sources to not "contaminate" the license of the project with a different license for those source files.

I also agree that clarifying this explicitly for legal purposes is a good thing.

**Comment by sappo** [comment]
Sounds good to me!

@jimklimov there is already a short paragraph about the license.xml in the README. (https://github.com/zeromq/zproject#toc2-121)
