### ISSUE TITLE
Problem: need to maintain template files not generated by zproject

### ISSUE THREAD

**Issue by jimklimov** [zeromq/zproject#800]
Solution: similar to what is done by `<bin>` tag for scripts and `<extra>` for "other files", add support in `project.xml` for template (`*.in`) files (to generate entries into `configure.ac` and `.gitignore` and `Makefile / EXTRA_DIST` - installation and dstribution may be handled by e.g. `Makemodule-local.am`).

**Comment by bluca** [comment]
There's also an autoconf local hook (acinclude.m4) so project-local AC_CONFIG_FILES and EXTRA_DIST can be added (and also for CMake there's a local hook)

**Comment by bluca** [comment]
A few examples in case they can be useful:

https://github.com/zeromq/malamute/blob/master/acinclude.m4
https://github.com/zeromq/zyre/blob/master/acinclude.m4
https://github.com/zeromq/zyre/blob/master/src/Makemodule-local.am
https://github.com/zeromq/zyre/blob/master/src/CMakeLists-local.txt

**Comment by jimklimov** [comment]
Addressed back then but not closed, in commits around PR #1079 and #1078 with origins from #202 and #768
