### ISSUE TITLE
Problem: zinstall might not be the solution

### ISSUE THREAD

**Issue by sappo** [zeromq/zproject#834]
Continuing the discussion from #825.

@vyskocilm thanks for the thorough explanation!

@vyskocilm @bluca @jimklimov Here's what I think about the current solution:
* zinstall is not installing anything but providing snippets for other files!
* There is no need to store those snippets in actual files in each project. This just feels weird.

Here's what I propose:
1. Move everything concerning systemd into it's own target, i.e. `zproject_systemd`.
2. Allow targets like autotools to register a snippet hook for its various files.
3. Now the systemd target will provide the autotools target with snippets which are inserted during code generation and thus not stored on each user's project.

As a result the systemd stuff will vanish from the autotools, debian and redhat gsl files making them more readable and targets that scatter their stuff all over the place can be contained into one file.

Questions!? Remarks!?

**Comment by jimklimov** [comment]
Such modularity makes sense to me - I think for autotools (and configure script) the reasonable approach would be to populate relevant files into the `projectroot/m4` directory and referencing the file by a single command in `configure.ac`. And of course pre-generate (the .in templates for) actual configs, units, includable pieces of the Makefile to set up install location and dist/clean requirements, etc.

Just as well, the common bit in the configure script might gain a `--with-user=...` and `--with-group=...` arguments (defaulted to `nobody`?) so a distro maintainer can specify which credentials the built daemons/services will run in his OS.

This could be non-invasively (readability!) generalized for other frameworks, like init-scripts for older distributions and SMF manifests and methods for Solarish systems, for example.

**Comment by vyskocilm** [comment]
OK I see your main complaint now! You don't like the fact zproject_install and rest of the zproject scripts communicates using files :) All it needs is someone with much better gsl skills than I have.
