### ISSUE TITLE
zproject completely broken

### ISSUE THREAD

**Issue by karolhrdina** [zeromq/zproject#902]
Given the following `project.xml` template:
```
<project
    name = "aoc2016"
    script = "zproject.gsl"
    >

    <use project = "czmq" />

    <class name = "rob" private = "1">todo</class>
    <main name = "task_01" />
</project>
```

when i try to use `rob` class in main task_01.c, i.e. add the following three lines into task_01.c:
```
    rob_t *x = rob_new ();
    assert (x);
    rob_destroy (&x);
```

i get the following linker error
```
src/src_task_01-task_01.o: In function `main':
/home/kj/temp/AoC_2016/src/task_01.c:42: undefined reference to `rob_new'
/home/kj/temp/AoC_2016/src/task_01.c:44: undefined reference to `rob_destroy'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: src/.libs/task_01: hidden symbol `rob_new' isn't defined
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Makefile:889: recipe for target 'src/task_01' failed
make[1]: *** [src/task_01] Error 1
```

**Comment by jimklimov** [comment]
Guesswork: private class, non-draft build?.. :\

**Comment by sappo** [comment]
@karolhrdina the reason is this define:
```
#       define AOC2016_PRIVATE __attribute__ ((visibility ("hidden")))
```

**Comment by bluca** [comment]
The problem is that it's trying to use a private class, of which the symbols are intentionally not exported, from another external binary executable.

If a class is to be used in another binary executable that links against the library, then it follows it shouldn't be private, but public

**Comment by karolhrdina** [comment]
Aarrrggh.... 
You're of course right -- the private attribute is doing it's job.
Sleep deprivation got the best out of me.

I apologize for false alarm.

Thank you.
