### ISSUE TITLE
Python bindings don't restore pwd if libczmq installed elsewhere

### ISSUE THREAD

**Issue by jimrthy** [zeromq/zproject#904]
If libczmq isn't installed in the location the python bindings are expected, it pretty much fails silently and changes the current working directory.
The latter problem (which is annoying to debug) is easy to fix: just wrap a try/finally around the "change directory back" code.
Since this gets into the "real" code generation, it seemed like a good issue for me to cut my zproject teeth on.
So I've been trying to follow along with the steps in the README.
When I look at the changes made to malamute, zyre, and czmq under the gitprojects folder (created by running tstgenbld.sh), both before and after, I see:
a) changes that I didn't expect: 
  -- lots of things under Malamute like the ci_build.sh
  -- changes to the way zyre and czmq import their cffi bindings, which I didn't touch
b) nothing related to my actual changes
So it looks like I also need to use GSL to rebuild the associated bindings under czmq, malamute, and zyre. Do I need to set up parallel PRs for the changes I want to make there, or will that part get picked up automatically, assuming the PR I submit here gets accepted?

**Comment by bluca** [comment]
If it's the path to the libraries that's changing, check that you have all 3 in the same directory, and that they are called czmq and zyre, and not something else like libczmq

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/zproject/pull/905
