### ISSUE TITLE
Missing target version

### ISSUE THREAD

**Issue by diorcety** [zeromq/zproject#907]
The SOVERSION is defined for the target but not the VERSION. Which imply that the libxxx.so.M.N.R is created but not libxxx.so.M. The python wrappers fail to find the libraries when compiling them with cmake

**Comment by bluca** [comment]
Are you referring to cmake? Could you send a PR to fix it please?

**Comment by vyskocilm** [comment]
Hi, our looks like fix had been merged by @bluca closed
