### ISSUE TITLE
jni singleton methods aren't static

### ISSUE THREAD

**Issue by jimrthy** [zeromq/zproject#909]
This shows up in 2 places right off the bat:
1. You can't call Zsock.newPull() to create a PULL socket (or any other variant on this theme).
2. You can't call Zframe.recv()

Instead, you have to create a new instance of some kind of socket that you might not care about in order to create the one you do. And then create a new instance of Zframe that you almost definitely don't want in order to recv messages.

**Comment by jimrthy** [comment]
Is there any sort of community process for closing an issue that I wrote up and fixed myself? I should I just close this one because I think it's done?

**Comment by bluca** [comment]
Yes, just mention the PR that fixed it and close the issue. Thanks!

**Comment by jimrthy** [comment]
I think https://github.com/zeromq/zproject/issues/910 fixes it.
