### ISSUE TITLE
Problem: Cannot define private methods in the API

### ISSUE THREAD

**Issue by eponsko** [zeromq/zproject#945]
I would like to be able to define methods as private, in public classes.
The idea would be to have something package-private methods, like in Java. 

**Solution:** Write private methods into project_classes.h

The XML definition would look something like this:
```
<class name="my public class">
  <method name="public method">
    Does stuff anyone is allowed to do
   <return type="nothing"/>
  </method>
 <method name="private method" private = "1">
   Does stuff only part of the library is allowed to do
   <return type="nothing"/>
 </method>
</class
```

Implementation in pull request #944

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/zproject/pull/944
