### ISSUE TITLE
Problem: JNI generator generates invalid code if a reserved Java keyword is used

### ISSUE THREAD

**Issue by sappo** [zeromq/zproject#947]
Prefix or Suffix the variable/function to escape the issue

**Comment by jimklimov** [comment]
FWIW, here is a helpful list of the 53 reserved keywords in Java (to help make a generic solution, rather than a "real fix" for https://github.com/zeromq/czmq/issues/1719 alone) : https://en.wikipedia.org/wiki/List_of_Java_keywords

**Comment by bluca** [comment]
We have the same problem with Python and zyre now - the zyre_peer class has a "print" API, which clashes with Python's print function.

So it looks like a generic way to handle reserved keyword in zproject bindings generation is what we need

**Comment by bluca** [comment]
There is another problem with return types:

```
--- a/bindings/jni/src/main/java/org/zeromq/czmq/Zconfig.java
+++ b/bindings/jni/src/main/java/org/zeromq/czmq/Zconfig.java
@@ -229,10 +229,9 @@ public class Zconfig implements AutoCloseable{
     }
     /*
     Destroy node and subtree (all children)
-    WARNING: manually fixed void -> long
     */
     native static long __remove (long self);
-    public long remove () {
+    public void remove () {
         self = __remove (self);
         return 0;
     }
```

Manually fixed in https://github.com/zeromq/czmq/pull/1822 but needs a resolution in the zproject template (not sure how though)

**Comment by hgourvest** [comment]
fixed with this merge https://github.com/zeromq/zproject/pull/1133
