### ISSUE TITLE
gsl project.xml don't generate some files.

### ISSUE THREAD

**Issue by diorcety** [zeromq/zproject#979]
gsl project.xml doesn't regenerate api/*.api files

**Comment by diorcety** [comment]
I updated gsl  zproject  zproto to master branch, if i delete api/*.api and run gsl project.xml, nothing is generated

**Comment by bluca** [comment]
Well yes, the .api files are written by developers, they are not generated. They are used to generate the rest.

**Comment by diorcety** [comment]
The file header say that is 100% generated code. ??

**Comment by bluca** [comment]
Which ones?

**Comment by diorcety** [comment]
https://github.com/zeromq/malamute/blob/master/api/mlm_client.api

**Comment by diorcety** [comment]
Is it generated: see https://github.com/zeromq/malamute/commit/53d326e09666a6e834ea0e00fe4f4c5cfee0b2f1#diff-de58b610ec3927786e5ead1e0a7479e1R136

**Comment by bluca** [comment]
Right - that one is a special case, as it's generated by zproto. There's a "make code" target as a shortcut.

In general, api/*api files are hand-written, like these:

https://github.com/zeromq/czmq/tree/master/api

and these:

https://github.com/zeromq/zyre/tree/master/api

**Comment by vyskocilm** [comment]
Or in the other words, generated source files have generated API files.
Hand written files have hand written one 😀

Dne 6. 10. 2017 1:15 odpoledne napsal uživatel "Luca Boccassi" <
notifications@github.com>:

**Comment by diorcety** [comment]
I reported few issues 
https://github.com/zeromq/malamute/issues/289
https://github.com/zeromq/zproto/issues/378

Some clean up is needed

**Comment by vyskocilm** [comment]
OK, I'll close this issue and will look on others.
